version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: kittygram
      POSTGRES_USER: kittygram_user
      POSTGRES_PASSWORD: kittygram_password
    ports:
      - "5432:5432"
  backend:
    image: artemproyd/backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      -  media:/app/media/
  frontend:
    image: artemproyd/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: artemproyd/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
      - media:/media/
    ports:
      - 9000:80

